<a href="https://colab.research.google.com/github/rsher60/LLM_Codebase/blob/main/fine_tuning_Ed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# imports

import os
import random
from dotenv import load_dotenv
from huggingface_hub import login
from datasets import load_dataset, Dataset, DatasetDict

from items import Item

import matplotlib.pyplot as plt
from collections import Counter, defaultdict
import numpy as np
import pickle

In [2]:
!pip install -q typing transformers datasets python_dotenv

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.6/78.6 kB 2.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 10.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 10.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 17.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 13.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 16.2 MB/s eta 0:00:00
  Building wheel for typing (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.

In [6]:
from typing import Optional
from transformers import AutoTokenizer
import re
from datasets import load_dataset

In [62]:
data = load_dataset("pgurazada1/amazon_india_products")["train"]

In [63]:
# Investigate a particular datapoint
datapoint = data[2]

In [64]:
datapoint

{'Uniq Id': '41654633cce38c8650690f6dbac01fd3',
 'Crawl Timestamp': '2019-10-30 09:53:23 +0000',
 'Category': 'Skin Care',
 'Product Title': ' Generic 1 Pc brand snail eye cream remove dark circle eye lifting instant ageless snail cream for eye care anti wrinkle eyes cream 20g ',
 'Product Description': 'Use: eye, item type: cream, net wt: 20g, gzzz: ygzwbz, model number: lkwnys, gender: female, certification: gzzz, feature: moisturizing, dark circle, anti-puffiness, anti-aging, brand name: laikou, certificate number: 2014028630, ingredient: cream, country/region of manufacture: china, eye care features: eye cream, product name: snail extract cream, applicable to the crowd: general, specifications: normal specifications, origin: shantou, guangdong province, unit type: piece, package weight: ,package size:',
 'Brand': 'Generic',
 'Pack Size Or Quantity': None,
 'Mrp': '1824.00',
 'Price': '1042.00',
 'Site Name': 'Amazon In',
 'Offers': '42.87%',
 'Combo Offers': None,
 'Stock Availibility': 'YES',
 'Product Asin': 'B07DCSN8MP',
 'Image Urls': 'https://images-na.ssl-images-amazon.com/images/I/51bWWBIkeZL._AC_US40_.jpg|https://images-na.ssl-images-amazon.com/images/I/51bWWBIkeZL._AC_US40_.jpg|https://images-na.ssl-images-amazon.com/images/I/51FWHBskhHL._AC_US40_.jpg|https://images-na.ssl-images-amazon.com/images/I/51uynr8t2tL._AC_US40_.jpg|https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/transparent-pixel._V192234675_.gif'}

In [65]:
# How many have prices?

prices = 0
for datapoint in data:
    try:
        price = float(datapoint["Mrp"] or 0.0)
        if price > 0.0:
            prices += 1
    except ValueError as e:
        pass

print(f"There are {prices:,} with prices which is {prices/len(data)*100:,.1f}%")

There are 29,240 with prices which is 97.5%

In [78]:
import pandas as pd
df  = pd.DataFrame(data)

In [79]:
#Drop the rows where the price is none and then delete rows where price is 0.0

df = df.dropna(subset=['Mrp'])

In [80]:
df.dtypes

Uniq Id                  object
Crawl Timestamp          object
Category                 object
Product Title            object
Product Description      object
Brand                    object
Pack Size Or Quantity    object
Mrp                      object
Price                    object
Site Name                object
Offers                   object
Combo Offers             object
Stock Availibility       object
Product Asin             object
Image Urls               object
dtype: object

In [84]:
clean_price('2.4.00')

'24.00'

In [85]:
# CHange the data tyoe of the column to float

import re

def clean_price(price_str):
  """Cleans a price string by removing extra decimal points."""
  if price_str.count('.') ==2:
    cleaned_price = re.sub(r"\.", "", price_str.strip(), count=1)
    return cleaned_price
  else:
    return price_str

In [86]:
# apply the clean price function

df['Mrp'] = df['Mrp'].apply(lambda x : float(clean_price(x) or 0.0))

Uniq Id                   object
Crawl Timestamp           object
Category                  object
Product Title             object
Product Description       object
Brand                     object
Pack Size Or Quantity     object
Mrp                      float64
Price                     object
Site Name                 object
Offers                    object
Combo Offers              object
Stock Availibility        object
Product Asin              object
Image Urls                object
dtype: object

In [61]:
#count the number of .

dr = 'dfbfddf.232.'


dr.count('.')

2

In [60]:
df.head(40)

,Uniq Id,Crawl Timestamp,Category,Product Title,Product Description,Brand,Pack Size Or Quantity,Mrp,Price,Site Name,Offers,Combo Offers,Stock Availibility,Product Asin,Image Urls
0,eb49cc038190f6f03c272f79fbbce894,2019-10-30 11:38:11 +0000,Skin Care,Lee posh Lactic Acid 60% Anti ageing Pigmenta...,PROFESSIONAL GRADE Face Peel: this peel stimul...,Lee Posh,None,200000.0,799.00,Amazon In,60.05%,None,YES,B072BGHNJ1,https://images-na.ssl-images-amazon.com/images...
1,1657cc30c438affede6a5060d6847363,2019-10-31 15:46:54 +0000,Skin Care,Branded SLB Works New 1.5mm Titanium 1200 nee...,Item name: 1.5mm titanium 1200 needles microne...,SLB Works,None,204000.0,2040.00,Amazon In,0%,None,YES,B07QDTZYSJ,https://images-na.ssl-images-amazon.com/images...
2,41654633cce38c8650690f6dbac01fd3,2019-10-30 09:53:23 +0000,Skin Care,Generic 1 Pc brand snail eye cream remove dar...,"Use: eye, item type: cream, net wt: 20g, gzzz:...",Generic,None,182400.0,1042.00,Amazon In,42.87%,None,YES,B07DCSN8MP,https://images-na.ssl-images-amazon.com/images...
3,08b1bd85c3efc2d7aa556fd79b073382,2019-10-29 16:16:52 +0000,Skin Care,Generic Anti Snoring Snore Stopper Sleep Apne...,Prevent the tongue from dropping backward or b...,Generic,None,218500.0,1399.00,Amazon In,35.97%,None,YES,B07GLW9VQN,https://images-na.ssl-images-amazon.com/images...
4,3ac3f213732512d1d11bb73ab3b1900f,2019-10-31 09:32:06 +0000,Grocery & Gourmet Foods,Harveys Crunchy & Creame Gourmet Delicacies C...,Harvey's wafer Cream Wafer 110g. Made in India,Harveys,None,59400.0,570.00,Amazon In,4.04%,None,YES,B07NFYYLF1,https://images-na.ssl-images-amazon.com/images...
5,f89b246d4e27c11623dbc7742523f319,2019-10-30 19:14:20 +0000,Skin Care,"Shikai Borage Dry Skin Therapy Foot Cream, 4....","Package Quantity:3 Contains borage oil, clinic...",ShiKai,354 g,534400.0,5344.00,Amazon In,0%,None,YES,B001ET7E8C,https://images-na.ssl-images-amazon.com/images...
6,ddb01f73b53ea264c0a9fcc31b1dbd72,2019-10-30 07:46:44 +0000,Bath & Shower,Black & Tan Beer Soap 4-Pack,Our handmade soaps are made with the highest g...,Lather+%26+Fizz+Bath+Boutique,None,908600.0,7269.00,Amazon In,20.0%,None,YES,B06XSRZV65,https://images-na.ssl-images-amazon.com/images...
7,516c5986d5dc20efaa37a58cbdea755a,2019-10-31 07:16:31 +0000,Bath & Shower,Mydio 2 Pack Waterproof Women Shower Caps Bat...,Mydio 2 Pack Waterproof Women Shower Caps Bath...,Mydio,49.9 g,165900.0,1659.00,Amazon In,0%,None,YES,B074FVJN7D,https://images-na.ssl-images-amazon.com/images...
8,fc4d5d08dcad5e10f3408e89990065a0,2019-10-28 16:33:56 +0000,Grocery & Gourmet Foods,Food Studio Premium Quality in Shell Pistachi...,Pistachios are small in appearance and are enc...,FOODSTUDIO,399 Grams,76000.0,660.00,Amazon In,13.16%,None,YES,B07Y3PTX42,https://images-na.ssl-images-amazon.com/images...
9,306bc2d444aa62cd53eb46fdbfd5c6f5,2019-10-28 16:57:50 +0000,Grocery & Gourmet Foods,Dr Glutens Gluten Free Khracker (KHAKHRA) - 2...,GLUTEN FREE KHAKHRAS. LIGHT HEALTHY AND ROASTE...,Dr Gluten,None,27900.0,279.00,Amazon In,0%,None,YES,B07Y4SSRR1,https://images-na.ssl-images-amazon.com/images...
10,e7ddc8be1bac2d440e7b48eea054fb4e,2019-10-29 04:42:46 +0000,Bath & Shower,Dermisa Soap Sulfur Facial 3 Ounce (88ml) (3 ...,This product is not eligible for priority ship...,Dermisa,None,524900.0,4199.00,Amazon In,20.0%,None,YES,B06XT2PQSD,https://images-na.ssl-images-amazon.com/images...
11,a9914e9c54f2fc517f85b0f336dac0e2,2019-10-29 16:26:58 +0000,Grocery & Gourmet Foods,Stubbs Pork Marinade (12 Oz Bottles) 2 Pack,"Stubb Loved To Cook Pork, Or €Œpig€ As He Cal...",Stubb%27s,None,512000.0,5120.00,Amazon In,0%,None,YES,B07QM7PHWL,https://images-na.ssl-images-amazon.com/images...
12,a47e15fd47e09231ab228367ed088348,2019-10-28 21:52:22 +0000,Grocery & Gourmet Foods,Dry Fruit Hub Date Crown Fard Dates Original ...,"Dates are the fruit of the date palm tree, whi...",DRY FRUIT HUB,None,39000.0,325.00,Amazon In,16.67%,None,YES,B07WKVRD68,https://images-na.ssl-images-amazon.com/images...
13,9e1ad76cd98a53227937ee8c20ac86bb,2019-10-30 13:20:12 +0000,Skin Care,SIGN EVER Ramacham Loffah Scrubber For Bathin...,Experience nature at its fullest with our natu...,SIGN EVER,None,28900.0,289.00,Amazon In,0%,None,YES,B07TJ1Q8FC,https://images-na.ssl-images-amazon.com/images...
14,a27e8ca25e5441693df6c764bfccf07a,2019-10-31 04:33:31 +0000,Skin Care,Rustic Rituals Dual Sided Dry Skin Body Brush...,Rustic rituals 2in1 dual sided bath brush with...,Rustic Rituals,200 g,119900.0,499.00,Amazon In,58.38%,None,YES,B07GVFDFG6,https://images-na.ssl-images-amazon.com/images...
15,dfaa7b5ae6027134dfe90eaeb9be61a7,2019-10-29 03:26:30 +0000,Grocery & Gourmet Foods,"Bogatchi Happy Anniversary Chocolates, Travel...",Bogatchi anniversary special chocolate. Luxuri...,BOGATCHI,181 Grams,59900.0,598.00,Amazon In,0.17%,None,YES,B06Y4BJCYJ,https://images-na.ssl-images-amazon.com/images...
16,a679bd6e1ed06554b42c9d4bc5bf3899,2019-10-29 19:18:21 +0000,Grocery & Gourmet Foods,Kamdaar Dry Fruits Roseberry Plum Weight 250 ...,KAMDAR DRY FRUITS brand brings you dried fruit...,KAMDAR DRY FRUITS,None,95000.0,650.00,Amazon In,31.58%,None,YES,B07V4WQQFW,https://images-na.ssl-images-amazon.com/images...
17,374ef0b2dc86f5f9baf0fb013ab4ab99,2019-10-31 00:12:15 +0000,Skin Care,NUBIAN HERITAGE BODY WASH,"NUBIAN HERITAGE BODY WASH,GOATS MLK&CHAI, 13 F...",NUBIAN,816 g,454400.0,4544.00,Amazon In,0%,None,YES,B001F1U044,https://images-na.ssl-images-amazon.com/images...
18,2a2a900c4b9112a0157279e7b0ec43e0,2019-10-30 17:20:26 +0000,Skin Care,Generic 8000Rpm Micro Vibration Massage Comb ...,Features: 1. 8000 times per minute micro vibra...,Generic,None,220600.0,1651.00,Amazon In,25.16%,None,YES,B07G4CS62D,https://images-na.ssl-images-amazon.com/images...
19,a29704747d62747acb0a7466fba4f9e9,2019-10-30 19:22:59 +0000,Skin Care,Beauche Kojic Beauty Soap Bar-90Grams,From Beauche International Beauche Beauty Soap...,Beauche International,9.07 g,329900.0,1033.00,Amazon In,68.69%,None,YES,B00L1MJQEM,https://images-na.ssl-images-amazon.com/images...
20,1da2e7e1689b4770449da46c4b0094f3,2019-10-31 15:46:26 +0000,Skin Care,"Innisfree Black Green-Tea Serum 50ml "" 2016 N...","Innisfree,InnisfreeR61818BeautyMisc",Innisfree,None,409100.0,4091.00,Amazon In,0%,None,YES,B01MRE01TH,https://images-na.ssl-images-amazon.com/images...
21,f8a030923ea8e1bceb845b5f5aa4e531,2019-10-31 00:12:20 +0000,Skin Care,Stockout SEPHORA COLLECTION Colorful Shadow &...,"These jumbo pencils create a range of effects,...",Stockout,None,1109700.0,3699.00,Amazon In,66.67%,None,YES,B07V2G5LB2,https://images-na.ssl-images-amazon.com/images...
22,d3dc01d74b62d77e553446bb45940f87,2019-10-29 00:11:04 +0000,Bath & Shower,Greenwood Essential Pure Turmeric Essential O...,Greenwood Essential pure turmeric essential oi...,Greenwood Essential,None,37400.0,207.00,Amazon In,44.65%,None,YES,B07KSB1BSZ,https://images-na.ssl-images-amazon.com/images...
23,ba21ee7182bbc08eb0a82ae2e363855e,2019-10-28 23:14:39 +0000,Skin Care,Detox Mask,ApplyTwice is the only store offering 100% Nat...,ApplyTwice,None,200000.0,1499.00,Amazon In,25.05%,None,YES,B07Q2R4CKY,https://images-na.ssl-images-amazon.com/images...
24,0ff6f31bc16523bbb6c9ded0d4df32b1,2019-10-31 15:59:43 +0000,Bath & Shower,"SOS Organics Natural Shaving Bar, 100 gm, Pac...",NATURAL SHAVING BAR. Take a look at the list o...,SOS Organics,None,34000.0,340.00,Amazon In,0%,None,YES,B07WSBSS58,https://images-na.ssl-images-amazon.com/images...
25,deb1658d991b425650af5953e1a544dd,2019-10-29 22:39:09 +0000,Skin Care,PINK PLUMS Neem-Tulsi with Vitamin E Massage ...,PINK PLUMS Massage Cream treatment using the p...,PINK PLUMS,None,99900.0,179.00,Amazon In,82.08%,None,YES,B07T1682KT,https://images-na.ssl-images-amazon.com/images...
26,367fdc141ec9b8121e770f26d3e77c03,2019-10-28 21:20:30 +0000,Grocery & Gourmet Foods,"Dadi Basmati Rice Supreme, 1000 grams",This product from the house of Dadi comes with...,Dadi,None,24500.0,245.00,Amazon In,0%,None,YES,B01N0T24S8,https://images-na.ssl-images-amazon.com/images...
27,9cefa5b902cb0765c09c9ea81104d42b,2019-10-30 01:51:34 +0000,Grocery & Gourmet Foods,Midiron Happy Friendship Day Quoted Printed C...,Midiron Chocolate Gifts Pack for Friends that ...,Midiron,None,99900.0,399.00,Amazon In,60.06%,None,YES,B07VQZ362F,https://images-na.ssl-images-amazon.com/images...
28,5029ab0b1af21904fc60942eeb8d870c,2019-10-30 19:16:10 +0000,Fragrance,Exotix Fragrance Chandan and Black Rose Attar...,A Non- Alcoholic Attar Concentrated Perfume Oi...,Exotix Fragrance,None,149900.0,888.00,Amazon In,40.76%,None,YES,B07X19G44G,https://images-na.ssl-images-amazon.com/images...
29,b4a99c9083e9ee24c456ca61f9a384df,2019-10-30 13:21:40 +0000,Grocery & Gourmet Foods,"Twizzlers Twists, Strawberry Flavored Licoric...",Twizzlers Twists Are A Movie-Theater Treat Wor...,Twizzlers,None,640000.0,6400.00,Amazon In,0%,None,YES,B07QL7ZY18,https://images-na.ssl-images-amazon.com/images...
30,7880fa31a8f0d3ff5be3f581dc8f5e58,2019-10-30 02:24:50 +0000,Skin Care,Armaf Eternia Perfume Body Spray for Men - 20...,Armaf Eternia deodorant is an irresistible uni...,ARMAF,None,29900.0,295.00,Amazon In,1.34%,None,YES,B07XYFCDGM,https://images-na.ssl-images-amazon.com/images...
31,074a7aec96cc5017099765c7f1df3010,2019-10-31 17:08:14 +0000,Skin Care,"Dionis Goat Milk Skincare - Lotion, 8.5 oz., ...",Size:8.50 oz. | Color:Vanilla Bean,Dionis,None,397400.0,3179.00,Amazon In,20.01%,None,YES,B06XT1LNJK,https://images-na.ssl-images-amazon.com/images...
32,98cbb7b0611dd7d13160ed768dcb12a9,2019-10-30 08:43:21 +0000,Grocery & Gourmet Foods,"Valentine Gifts for Boyfriend, Luxury Chocola...",De'arco chocolates are handpicked collection o...,De'Arco Chocolatier,254 Grams,219900.0,2199.00,Amazon In,0%,None,YES,B01N6XOXNV,https://images-na.ssl-images-amazon.com/images...
33,dfb803f526473074012a285630de2b7e,2019-10-29 20:45:22 +0000,Skin Care,ECO AMENITIES Transparent Tube Flip Cap Indiv...,ECO AMENITIES Transparent Tube Flip Cap Indivi...,Nvey Eco,None,503600.0,5036.00,Amazon In,0%,None,YES,B01CAHSL6K,https://images-na.ssl-images-amazon.com/images...
34,66bc998ca30c018789eb07192d1bb66d,2019-10-31 09:52:26 +0000,Grocery & Gourmet Foods,"Dhanvanthaari Curry Leaves Powder, 100 Grams ...",The secret ingredient in your lip-smacking veg...,Dhanvanthaari,200 Grams,22000.0,198.00,Amazon In,10.0%,None,YES,B07FM5DJ3B,https://images-na.ssl-images-amazon.com/images...
35,3dc0d72827f33fdbca0c2ff083423208,2019-10-30 17:03:36 +0000,Skin Care,[Innisfree] Soybean Energy Essence Light 150ml,This light-textured essential essence concentr...,Innisfree,231 g,516600.0,3089.00,Amazon In,40.21%,None,YES,B00OOFIDHY,https://images-na.ssl-images-amazon.com/images...
36,b1fed3cdb963fe48885d9540e4c44ed2,2019-10-30 01:02:40 +0000,Grocery & Gourmet Foods,"Dried Apricot khurmani, 250GM",Apricots khurmani 250GM with free shipping any...,Miltop,None,29100.0,275.00,Amazon In,5.5%,None,YES,B078MJFHY2,https://images-na.ssl-images-amazon.com/images...
37,4941bb1f448f4d00be75706c62429136,2019-10-30 21:27:13 +0000,Skin Care,Aveeno Moisturizing Bar for Dry Skin 3 Oz (Pa...,"Size:Pack of 4 Perfect for dry skin, this mild...",Aveeno,None,579900.0,3595.00,Amazon In,38.01%,None,YES,B00GB9O9CO,https://images-na.ssl-images-amazon.com/images...
38,7c954e6be8eb239fee0bd24ddc278f98,2019-10-31 05:48:05 +0000,Fragrance,Coach New York Platinum Eau de Parfum and All...,COACH was founded in 1941 in the heart of new ...,,99.8 g,447500.0,4475.00,Amazon In,0%,None,YES,B07JCY1YHY,https://images-na.ssl-images-amazon.com/images...
39,bd349d360d407b6f624ddc1744726266,2019-10-31 09:33:37 +0000,Skin Care,BAW Aloe : Collagen Essence Facial Mask Sheet...,"Item Type: Treatment & Mask, Feature: Oil-cont...",BAW,None,56800.0,568.00,Amazon In,0%,None,YES,B07YHX11MF,https://images-na.ssl-images-amazon.com/images...

In [30]:
df['Mrp'] = df['Mrp'].astype('float64')

ValueError: could not convert string to float: '.250.00'

In [14]:
df.shape

(29400, 15)

In [45]:
# change the datatyoe of the Price column to be numberic

Uniq Id                  object
Crawl Timestamp          object
Category                 object
Product Title            object
Product Description      object
Brand                    object
Pack Size Or Quantity    object
Mrp                      object
Price                    object
Site Name                object
Offers                   object
Combo Offers             object
Stock Availibility       object
Product Asin             object
Image Urls               object
dtype: object

In [44]:
import pandas as pd
import matplotlib.pyplot as plt

# Create a series
series = df['Price']

# Plot a histogram
series.plot.hist()
plt.show()

TypeError: no numeric data to plot

In [6]:
df.columns

Index(['Uniq Id', 'Crawl Timestamp', 'Category', 'Product Title',
       'Product Description', 'Brand', 'Pack Size Or Quantity', 'Mrp', 'Price',
       'Site Name', 'Offers', 'Combo Offers', 'Stock Availibility',
       'Product Asin', 'Image Urls'],
      dtype='object')

In [12]:
items = ItemLoader("Amazon_India_Products").load()

NameError: name 'ItemLoader' is not defined

In [ ]:
BASE_MODEL = "meta-llama/Meta-Llama-3.1-8B"

In [ ]:
MIN_TOKENS = 150
MAX_TOKENS = 160

MIN_CHARS = 300
CEILING_CHARS = MAX_TOKENS * 7